apiVersion: apps/v1
kind: Deployment
metadata:
  name: "humongous-healthcare-api"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: "humongous-healthcare-api"
  template:
    metadata:
      labels:
        app: "humongous-healthcare-api"
    spec:
      containers:
      - name: "humongous-healthcare-api"
        image: "tawwinwithappplatformacrabouba.azurecr.io/humongous-healthcare-api:0.0.0"
        imagePullPolicy: IfNotPresent
        env:
          - name: CosmosDb__Account
            valueFrom:
              secretKeyRef:
               name: cosmosdb
               key: cosmosdb-account
          - name: CosmosDb__Key
            valueFrom:
              secretKeyRef:
               name: cosmosdb
               key: cosmosdb-key
          - name: CosmosDb__DatabaseName
            value: HealthCheckDB
          - name: CosmosDb__ContainerName
            value: HealthCheck
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /HealthCheck
            port: http
        livenessProbe:
          httpGet:
            path: /HealthCheck
            port: http
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 200m
            memory: 256Mi